services:
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -lc "npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      # helps with file watching on Windows
      - CHOKIDAR_USEPOLLING=true
